global:
  scrape_interval: 5s
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kafka_exporter"
    #metrics_path: /metrics
    static_configs:
      - targets: ["172.20.37.21:5556"]

  - job_name: "jmx_exporter"
    static_configs:
      - targets: ["172.20.37.21:8081"]