version: "3.5"
services:

  init:
    image: busybox:latest
    entrypoint: ["/bin/sh", "-c"]
    command: |
      - "chown 1001:1001 /kafka;"
    volumes:
      - ./data/kafka1:/kafka
    restart: 'no'


  kafka1:
    image: docker.io/bitnami/kafka:3.5
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9094:9094
      - 9999:9999
    restart: always
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv

      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,EXTERNAL://172.20.37.21:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

      - KAFKA_HEAP_OPTS=-Xmx2g -Xms2g
      - KAFKA_CFG_LOG_FLUSH_INTERVAL_MS=5000
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10000120
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1

      - JMX_PORT=9999
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=172.20.37.21 -Dcom.sun.management.jmxremote.rmi.port=9999

    volumes:
      - ./data/kafka1:/bitnami/kafka
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - demo

  kafka-ui:
    container_name: kafka-ui
    restart: always
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka1
    environment:
      KAFKA_CLUSTERS_0_NAME: cluster0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9999
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect0
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
    networks:
      - demo
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  connect:
    image: harbor.sdsp-dev.com/kafka-connect/mixed-kit:2.6.1.Final
    container_name: connect
    restart: always
    ports:
      - 8083:8083
      - 9998:9998
      - 8081:8081
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=demo_connect_configs
      - CONFIG_STORAGE_REPLICATION_FACTOR=1
      - OFFSET_STORAGE_TOPIC=demo_connect_offsets
      - OFFSET_STORAGE_REPLICATION_FACTOR:=1
      - STATUS_STORAGE_TOPIC=demo_connect_statuses
      - STATUS_STORAGE_REPLICATION_FACTOR=1
      - BOOTSTRAP_SERVERS=kafka1:9092
      - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - HOST_NAME=0.0.0.0
      - ADVERTISED_HOST_NAME=172.20.37.21
      - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8081:/kafka/etc/config.yml
      - JMXPORT=9998
      - JMXHOST=172.20.37.21
    networks:
      - demo
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  demo:
    external: true
    name: demo